### ISSUE TITLE
Large impassable window blocks component copy

### ISSUE THREAD

**Issue by illmoor** [MscrmTools/MsCrmTools.SolutionComponentsMover#31]
After selecting the solutions, the "Copy Solutions" button and leaving the components ticked, I select "OK" and am presented with this screen:

![image](https://user-images.githubusercontent.com/9261664/216486345-ecce893b-38ce-4c83-9398-f51f15683aef.png)

I cannot move the window or resize it, pressing enter, space, or ESC simply closes the window and no copy takes place (no messages in the output).

**Comment by MscrmTools** [comment]
Ok, the issue here is that your solution contains A LOT of managed entities added with all their assets. 
Best practices require that you only add changed sub components for a managed entity. 
To avoid this screen, untick the check box "Check bext practice before moving components" before copying components

![image](https://user-images.githubusercontent.com/10774317/216542793-24928ad3-d230-4447-b445-9bdcbf3f5964.png)

In the meantime, I will put only the 10 first entities in the message box so that it is user friendly
